# Generated by Django 4.1.2 on 2024-01-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20210303_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='Manager_city',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Manager_country',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Manager_pincode',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Manager_state',
        ),
    ]
