# Generated by Django 4.1.2 on 2024-01-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_pincode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_state',
        ),
    ]
