# Generated by Django 4.1.2 on 2024-01-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_auto_20210207_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='Owner_city',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='Owner_country',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='Owner_pincode',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='Owner_state',
        ),
    ]
